language: python
python:
  - "3.8"
install:
  - pip install pygal
  - pip install ipython
script:
  - python unittest_Monitoring.py
  - python unittest_Records.py
  - python cv_testsuit.py
  - python -m coverage run cb_testsuit.py
  - python -m coverage report